### ISSUE TITLE
Error setting up integration with Google Cloud SQL MySQL

### ISSUE THREAD

**Issue by KrisB88** [singer-io/tap-mysql#144]
I'm getting the error below when attempting to integrate with Google Cloud SQL. Any thoughts on how to resolve this?

`2021-05-11 23:51:37,933Z   main - INFO Running tap-mysql version 1.17.5 and target-stitch version 3.2.0
2021-05-11 23:51:38,099Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2021-05-11 23:51:38,102Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2021-05-11 23:51:38,103Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
2021-05-11 23:51:39,118Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [1] at offset None
2021-05-11 23:51:39,118Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-mysql --config /tmp/tap_discover_config.json --discover
2021-05-11 23:51:39,475Z    tap - CRITICAL cryptography is required for sha256_password or caching_sha2_password
2021-05-11 23:51:39,477Z    tap - Traceback (most recent call last):
2021-05-11 23:51:39,477Z    tap -   File "tap-env/bin/tap-mysql", line 33, in <module>
2021-05-11 23:51:39,477Z    tap -     sys.exit(load_entry_point('tap-mysql==1.17.5', 'console_scripts', 'tap-mysql')())
2021-05-11 23:51:39,477Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
2021-05-11 23:51:39,477Z    tap -     return fnc(*args, **kwargs)
2021-05-11 23:51:39,477Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_mysql/__init__.py", line 722, in main
2021-05-11 23:51:39,477Z    tap -     log_server_params(mysql_conn)
2021-05-11 23:51:39,477Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_mysql/__init__.py", line 683, in log_server_params
2021-05-11 23:51:39,477Z    tap -     with connect_with_backoff(mysql_conn) as open_conn:
2021-05-11 23:51:39,477Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff/_sync.py", line 94, in retry
2021-05-11 23:51:39,477Z    tap -     ret = target(*args, **kwargs)
2021-05-11 23:51:39,478Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_mysql/connection.py", line 24, in connect_with_backoff
2021-05-11 23:51:39,478Z    tap -     connection.connect()
2021-05-11 23:51:39,478Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymysql/connections.py", line 599, in connect
2021-05-11 23:51:39,478Z    tap -     self._request_authentication()
2021-05-11 23:51:39,478Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymysql/connections.py", line 871, in _request_authentication
2021-05-11 23:51:39,478Z    tap -     auth_packet = self._process_auth(plugin_name, auth_packet)
2021-05-11 23:51:39,478Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymysql/connections.py", line 902, in _process_auth
2021-05-11 23:51:39,478Z    tap -     return _auth.sha256_password_auth(self, auth_packet)
2021-05-11 23:51:39,478Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymysql/_auth.py", line 179, in sha256_password_auth
2021-05-11 23:51:39,478Z    tap -     data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
2021-05-11 23:51:39,478Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymysql/_auth.py", line 142, in sha2_rsa_encrypt
2021-05-11 23:51:39,478Z    tap -     raise RuntimeError("cryptography is required for sha256_password or caching_sha2_password")
2021-05-11 23:51:39,478Z    tap - RuntimeError: cryptography is required for sha256_password or caching_sha2_password
2021-05-11 23:51:39,511Z   main - INFO Tap exited abnormally with status 1
2021-05-11 23:51:40,111Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [31] at offset None
2021-05-11 23:51:40,112Z   main - INFO No tunnel subprocess to tear down
2021-05-11 23:51:40,112Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "cryptography is required for sha256_password or caching_sha2_password".`

**Comment by woochica** [comment]
I've just realized that your issue is the same as mine: https://github.com/singer-io/tap-mysql/issues/151
